/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 car.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/car.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Driveseat1Mtl} position={[-0.439, 1.03, -24.819]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.Meshpart1Mtl} position={[0.132, 4.623, -25.06]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.Meshpart3Mtl} position={[0.221, 3.134, -25.629]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Rr1Mtl} position={[0.093, 2.985, -23.949]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5001.geometry} material={materials.Rr1Mtl} position={[0.093, 2.985, -23.949]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/car.gltf')
